version: "3"

services:
  mongodb1:
    container_name: mongo1
    image: mongo
    build: "./set_primary/"
    restart: unless-stopped
    volumes:
      - ./volumes/mongodb1:/data/db
    ports:
      - "27011:27011"
    expose:
      - "27011"
    entrypoint:
      [
        "/bin/bash", "/root/entry.sh"
      ]

  mongodb2:
    container_name: mongo2
    image: mongo
    build: "./set/"
    restart: unless-stopped
    volumes:
      - ./volumes/mongodb2:/data/db
    ports:
      - "27012:27012"
    expose:
      - "27012"
    entrypoint:
      [
        "/usr/bin/mongod",
        "--port", "27012",
        "--replSet", "{REPLICATIONNAME}",
        "--bind_ip_all",
        "--keyFile", "/root/keyfile.key"
      ]

  mongodb3:
    container_name: mongo3
    image: mongo
    build: "./set/"
    restart: unless-stopped
    volumes:
      - ./volumes/mongodb3:/data/db
    ports:
      - "27013:27013"
    expose:
      - "27013"
    entrypoint:
      [
        "/usr/bin/mongod",
        "--port", "27013",
        "--replSet", "{REPLICATIONNAME}",
        "--bind_ip_all",
        "--keyFile", "/root/keyfile.key"
      ]
